os: osx
language: objective-c
sudo: false
osx_image: xcode10.1
matrix:
  include:
    - name: "Logic Tests / iPhone X / iOS 12.1 / Xcode 11.0 / macOS 10.14"
      osx_image: "xcode11.0"
      env: MIXBOX_CI_DESTINATION="iphone_x_ios121.json" MIXBOX_CI_BUILD_EXECUTABLE="TravisLogicTestsBuild" MIXBOX_CI_REPORTS_PATH="."
script:
    ci/swift/run_swift